#----------------------------SERVER PORT INITIALIZATION..
server.port=8090



#--------------------------------DATA BASE CONNECTIVITY ---------------
spring.application.name=mysqLRestAPI
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/todo_list
spring.datasource.username = root
spring.datasource.password = @n@ndA@321


